export const ADD_CONTACT_SUCCESS    = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAIL    = 'ADD_CONTACT_FAIL';
export const ADD_CONTACT_START =  'ADD_CONTACT_START';

export const FETCH_CONTACTS_START = 'FETCH_CONTACTS_START';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAIL = 'FETCH_CONTACTS_FAIL';

export const DELETE_CONTACT_START = 'DELETE_CONTACT_START';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';

export const EDIT_CONTACT_START = 'EDIT_CONTACT_START';
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_FAIL = 'EDIT_CONTACT_FAIL';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const SHOW_MODAL_CLOSE = 'SHOW_MODAL_CLOSE';
export const SHOW_MODAL_OPEN= 'SHOW_MODAL_OPEN';


